### ISSUE TITLE
Translator & AI Dungeon Multiplayer

### ISSUE THREAD

**Issue by Quizerxxxx** [d4n3436/Fergun#2]
Hey. What do you think about integrating Google Translate into AI Dungeon, how difficult is it? And is it possible to implement it?

**Comment by Quizerxxxx** [comment]
And also, I would like to clarify whether it is possible to make some kind of multiplayer, as on the site. To control two characters in one story?

**Comment by d4n3436** [comment]
Hello, thanks for the feedback.

> What do you think about integrating Google Translate into AI Dungeon, how difficult is it? And is it possible to implement it?

The Google Translate integration has been added into AI Dungeon a while ago. To enable it, use `f!config`, option 2.
Currently it only supports the languages available in `f!language` (Arabic, Spanish, Russian and Turkish) but I'm planning to add support to any language that Google Translate also supports.

> And also, I would like to clarify whether it is possible to make some kind of multiplayer, as on the site. To control two characters in one story?

I was digging through the AID websocket requests trying to recreate the multiplayer logic, but it seems pretty hard to implement in the bot since I have to reverse engineer all the requests related to the multiplayer: sessions, players, world info, quests, etc.
I also have to implement the multiplayer logic, the commands and the invite functionality into the bot module.

It will take some time to implement the multiplayer, plus I'm planning to redo the entire API wrapper from scratch using a GraphQL library because the current state of the wrapper makes it hard to maintain and add more features.

**Comment by Squizert** [comment]
Thanks for your work, it amazed me.

I decided to try to understand your bot and add something for myself. Could you tell me where can I find the AiDungeonToken

**Comment by d4n3436** [comment]
I'm closing this issue since I won't be adding any new features to the AI Dungeon module.
I lost interest in AI Dungeon some time ago, and I don't really want to spend time adding features to something I don't enjoy anymore.
I will keep maintaining the module, but only for fixing bugs.
If anyone wants to add the multiplayer functionality, feel free to make a PR, and I will add it to the repository.
